### ISSUE TITLE
Wrong output if no new lines

### ISSUE THREAD

**Issue by kaptenw** [seyedip/nested-css#1]
Hi,

I'm using this to parse the input of a textarea. If a user forgets to add a linebreak between `{` and a declaration this will break. It would be really nice if it worked without line breaks also, then you don't have to worry about the input formatting being "correct".

The following code works:
```
/* input */
a {
   color: blue;
   .button {
       padding:10px;
   }
}

/* output */
a{color: blue;}a .button{padding:10px;}
```

The following code doesn't work:
```
/* input */
a {
   color: blue;
   .button { padding:10px; }
}

/* output */
a{color: blue;}
```

**Comment by seyedip** [comment]
Hi there!  :)

I just fixed this issue you submitted. But still there are ways to break the compiler! For example: missing `;` when there is no newline before `}`.

This does not work:

```css
a{color:blue} 
```

But this will work:

```css
a{color:blue;}  /* added the semicolon */
/* without semicolon but with newline */
a{
   color: blue
}
```

We are not planning to fix every single edge case. nested_css only makes sense if you are willing to compromise convenience with performance.
